import type { ProductCopy } from './types';

export const zhCN = {
  app: {
    name: 'Jarvis',
    descriptor: '私人认知观测空间',
  },
  navigation: {
    label: '主要导航',
    current: '此刻',
    conversation: '对话',
    map: '星图',
    evolution: '演变',
    archive: '档案',
    settings: '设置',
    unavailable: '后续开放',
    unavailableDescription: '此入口将在后续阶段开放，当前不可使用。',
  },
  conversation: {
    backToPresence: '返回此刻',
    backToLatest: '回到最新回答',
    cancelled: '已停止',
    composerHint: 'Enter 发送，Shift+Enter 换行；中文输入法组合期间不会误发送。',
    composerStreamingHint: 'Jarvis 正在回答，你可以先整理下一条想法。',
    composerLabel: '继续这段讨论',
    composerPlaceholder: '写下还没有整理完整的想法……',
    contextTitle: '当前思维交汇',
    errorBody: '本地 Mock 回答没有完成。你的表达仍然保留，可以从同一回合重新尝试。',
    failed: '回答失败',
    mockDisclosure: '当前历史、模拟转录、跨领域联系与 Jarvis 回答均为确定性 Mock。',
    offlineBody: '仍可查看已有讨论，并继续使用不依赖网络的本地 Mock。',
    offlineTitle: '当前处于离线演示状态',
    retry: '重新尝试',
    send: '发送文字',
    stopGenerating: '停止生成',
    sourceText: '文字输入',
    sourceVoice: '模拟转录 · 真实录音',
    stopped: '这段回答已停止，已显示部分仍保留。',
    streaming: '正在形成回答',
    unknownBody: '这个探索编号不在当前演示数据中。你可以返回“此刻”，或进入默认讨论。',
    unknownTitle: '没有找到这段探索',
    voiceProfileFuture: '真正的声线选择将在真实 Provider 阶段接通。',
    voiceProfileSummary: '声线：默认演示声线',
  },
  presence: {
    eyebrow: '此刻 · 安静待命',
    activeExplorations: '正在探索',
    unresolvedQuestions: '尚未解开的疑问',
    recentCognition: '最近的认知变化',
    continueExploration: '继续探索',
    continueResponse: '已在当前页面展开这条探索线索。本轮不会调用模型或保存数据。',
    provisional: '待确认 · 暂存观察',
    updatedAt: '更新于',
    emptyTitle: '这里还没有被保留的探索。',
    emptyBody: '当一次对话真正改变了你的理解，Jarvis 才会邀请你确认并把它留在这里。',
    emptyHint: '你仍然可以先写下一个问题；本轮内容只停留在当前页面。',
    questionLabel: '写下一个问题',
    questionPlaceholder: '此刻，你想继续想清楚什么？',
    questionAction: '暂存问题',
    questionResponse: '问题已暂存在当前页面。关闭应用后不会保留，也不会发送给任何服务。',
    voiceAction: '按住说话',
    voiceDisclosure: '下一阶段接通 · 当前不会录音',
    voiceResponse: '语音尚未接通，本轮没有访问麦克风，也没有录制任何内容。',
    idleState: 'Jarvis 在场状态：安静待命',
    localMockDisclosure: '当前内容为开发阶段 Mock 数据',
    reducedMotionActive: '已减少动态效果：Orb 保持静态',
  },
  voice: {
    cancelAction: '取消本轮',
    demoDisclosure: '演示模式：录音与波形来自真实麦克风，转录和回答暂为模拟内容。',
    durationLabel: '录音时长',
    holdMode: '按住说话',
    holdModeDescription: '按住开始，松开发送。',
    mockBadge: '演示 Mock',
    modeLabel: '语音输入方式',
    noRoundYet: '点击后才会请求麦克风权限；应用启动时不会主动访问麦克风。',
    privacyDetails: [
      '麦克风只会在点击开始后，或按住说话期间采集。',
      '录音不会上传，也不会写入磁盘。',
      '点击发送或松开后，音频只为本地演示流程短暂保留在内存中。',
      '取消、错误或模拟转录生成后，临时音频会立即释放。',
    ],
    privacySummary: '本地音频与隐私边界',
    responseLabel: '模拟回答',
    retryAction: '重新尝试',
    roundTitle: '当前语音回合',
    state: {
      cancelled: {
        action: '本轮已取消',
        detail: '录音和临时资源已经释放。',
        label: '本轮已取消',
      },
      error: {
        action: '重新尝试',
        label: '语音暂时不可用',
      },
      idle: {
        action: '点击说话',
        detail: '点击开始录音，再次点击发送；也可以切换为按住说话。',
        label: '安静待命',
      },
      interrupted: {
        action: '回应已打断',
        detail: '正在准备新的语音输入。',
        label: '回应已打断',
      },
      listening: {
        action: '松开发送',
        detail: '按 Esc 取消',
        label: '正在聆听',
      },
      permissionRequest: {
        action: '正在请求麦克风权限',
        detail: '请在系统提示中选择是否允许；此刻尚未开始录音。',
        label: '正在请求麦克风权限',
      },
      respondingText: {
        action: '正在形成回答',
        detail: '回答正在以确定性片段显示。',
        label: '正在形成回答',
      },
      speaking: {
        action: 'Jarvis 正在回应',
        detail: '再次开始录音即可立即打断',
        label: '正在本地播放演示回应',
      },
      transcribing: {
        action: '正在生成模拟转录',
        detail: '录音已停止，临时音频将在模拟转录生成后释放。',
        label: '正在生成模拟转录',
      },
      understanding: {
        action: '正在整理问题',
        detail: '当前理解过程为确定性的本地 Mock。',
        label: '正在整理问题',
      },
    },
    transcriptLabel: '模拟转录',
    toggleMode: '点击说话',
    toggleModeDescription: '点击开始，再次点击发送。',
    toggleListeningAction: '再次点击发送',
    useTextAction: '继续使用文字',
  },
} satisfies ProductCopy;
